### ISSUE TITLE
Update to newest version (v3.5.0) of cytoscape.js 

### ISSUE THREAD

**Issue by nilshae** [rcarcasses/vue-cytoscape#11]
Is it possible to update the cytoscape dependency from 3.3.3 to 3.5.0? They added a [new curve-style](http://js.cytoscape.org/#style/taxi-edges), which I would like to include in my project.
Thank you!

**Comment by rcarcasses** [comment]
Hi there, currently the `cytoscape` dependency in `vue-cytoscape` is declared as `^3.3.3` as you can see in https://github.com/rcarcasses/vue-cytoscape/blob/b2a4fc7442855999be5832bda776ead52a5f9314/package.json#L26

This means that when you install `vue-cytoscape` the newest version of `cytoscape` within the same major range, currently `3`, will be used. You may find this tool useful:

https://semver.npmjs.com

I just double checked this by creating a fresh project only with `vue-cytoscape` package added and indeed it uses `cytoscape: 3.5.0`. 

I'm closing this since this is really not an issue. You are welcomed to create new ones :)

**Comment by nilshae** [comment]
I feel so dumb right now!  Thank you for the answer and sry for irrelevant issue.

**Comment by rcarcasses** [comment]
:)
